#include <iostream>
#include <fstream>
#include <vector>
#include <cstring>
#include "hybrid_encryption.h"
#include "dc_metadata.h"

using namespace std;

struct NALUInfo {
    uint32_t start_pos;
    uint32_t nal_pos;
    uint8_t type;
};

int main(int argc, char* argv[]) {
    if (argc != 3) {
        cerr << "Usage: " << argv[0] << " <input.h264> <key>\n";
        cerr << "Note: Requires nalu_info.bin generated by extract_nalu_from_h264analyze\n";
        return 1;
    }

    string input_file = argv[1];
    string key_str = argv[2];
    string output_file = input_file + ".s2_hybrid_fixed";
    string nalu_info_file = "nalu_info.bin";
    
    vector<uint8_t> key_bytes(key_str.begin(), key_str.end());

    // Load NALU info from h264_analyze
    ifstream nalu_info(nalu_info_file, ios::binary);
    if (!nalu_info) {
        cerr << "❌ Error: Cannot open " << nalu_info_file << "\n";
        cerr << "Run: extract_nalu_from_h264analyze " << input_file << "\n";
        return 1;
    }
    
    uint32_t nalu_count = 0;
    nalu_info.read((char*)&nalu_count, sizeof(nalu_count));
    
    vector<NALUInfo> nalus(nalu_count);
    for (uint32_t i = 0; i < nalu_count; i++) {
        nalu_info.read((char*)&nalus[i].start_pos, sizeof(nalus[i].start_pos));
        nalu_info.read((char*)&nalus[i].nal_pos, sizeof(nalus[i].nal_pos));
        nalu_info.read((char*)&nalus[i].type, sizeof(nalus[i].type));
    }
    nalu_info.close();

    ifstream input(input_file, ios::binary);
    if (!input) {
        cerr << "❌ Error: Cannot open input file: " << input_file << "\n";
        return 1;
    }
    
    vector<uint8_t> file_data((istreambuf_iterator<char>(input)), 
                              istreambuf_iterator<char>());
    input.close();

    cout << "📄 Input file: " << input_file << " (" << file_data.size() << " bytes)\n";
    cout << "🔑 Key: " << key_str << "\n";
    cout << "📊 Strategy: S2 (I-frames only, using h264_analyze NALU list)\n";
    cout << "🔍 Found " << nalu_count << " NAL units (from h264_analyze)\n";

    vector<uint8_t> encrypted_file_data = file_data;
    int encrypted_count = 0;
    
    cout << "\n🔐 Processing NALUs...\n";
    
    // For each NALU from h264_analyze
    for (size_t i = 0; i < nalus.size(); i++) {
        uint32_t start_code_pos = nalus[i].start_pos;
        uint32_t nal_byte_pos = nalus[i].nal_pos;
        int nal_type = nalus[i].type;
        
        // S2: Encrypt ONLY Type 5 (I-frames/IDR)
        if (nal_type != 5) {
            continue;
        }

        // NALU payload starts right after start code
        size_t nalu_payload_start = nal_byte_pos;
        
        // NALU payload ends at the next start code (or file end)
        size_t nalu_payload_end = file_data.size();
        if (i + 1 < nalus.size()) {
            nalu_payload_end = nalus[i+1].start_pos;
        }

        // Extract NALU payload
        vector<uint8_t> nalu_payload(
            file_data.begin() + nalu_payload_start,
            file_data.begin() + nalu_payload_end
        );

        // Extract DC coefficients (bytes 19-43, 25 bytes)
        if (nalu_payload.size() < 44) {
            continue;
        }

        vector<uint8_t> dc_data(nalu_payload.begin() + 19, 
                                nalu_payload.begin() + 44);
        
        // Apply hybrid encryption
        uint8_t padding_byte = 0;
        vector<uint8_t> encrypted_dc = HybridEncryption::encrypt_hybrid(
            dc_data, key_bytes, i, padding_byte
        );
        
        // Replace DC in NALU (encrypted_dc is 25 bytes: 24 encrypted + 1 padding)
        for (int j = 0; j < 25 && (nalu_payload_start + 19 + j) < encrypted_file_data.size(); j++) {
            encrypted_file_data[nalu_payload_start + 19 + j] = encrypted_dc[j];
        }
        
        encrypted_count++;
        
        if (i % 5000 == 0 && i > 0) {
            cout << "  Processed " << i << " NALUs...\n";
        }
    }
    
    // Write encrypted file
    ofstream output(output_file, ios::binary);
    output.write((char*)encrypted_file_data.data(), encrypted_file_data.size());
    output.close();

    // Write metadata
    string meta_file = output_file + ".meta";
    ofstream meta(meta_file);
    meta << "Strategy: S2 (I-frames only)\n";
    meta << "Total NALUs: " << nalu_count << "\n";
    meta << "Encrypted NALUs: " << encrypted_count << "\n";
    meta.close();

    cout << "\n✅ Fixed encryption complete!\n";
    cout << "  📊 Total NALUs: " << nalu_count << "\n";
    cout << "  🔐 Encrypted (Type 5 only): " << encrypted_count << "\n";
    cout << "  📄 Output file: " << output_file << " (" << encrypted_file_data.size() << " bytes)\n";
    cout << "  📋 Metadata file: " << meta_file << "\n";
    
    return 0;
}
